/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppButton: typeof import('./src/components/AppButton.vue')['default']
    FilterModal: typeof import('./src/components/FilterModal.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    JobCard: typeof import('./src/components/JobCard.vue')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    SearchBar: typeof import('./src/components/SearchBar.vue')['default']
  }
}
